environment:
  ARMADILLO_DOWNLOAD: "http://ftp.fau.de/macports/distfiles/armadillo/armadillo-8.400.0.tar.xz"
  BLAS_LIBRARY: "%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a"
  BLAS_LIBRARY_DLL: "%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll"
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDzP9Ow2mMpBe24ug1L4+k6+Hpd8XtdaxHn1Fg5x+AvylWpsdsO02i05CArOFvi6ljT8zYyki4D6fSubwNIvfBRsJQgweOjh/oyW2dFUG7bXegNpQSZv/bRCFnelqGaqF0GJWdw95NokPdnEmrTnEavAyJnZJdXL+2drvNVTzPhLBOzcFYF3YH2NEZ5KUt3SkUqy4O8jKFfBLQcw0K64VIFDX5nHrBspgfXQ/shbG8CNeqC0/74eYW/oH4tosnh0SyfxaeFF6hbboHtHv9ilDYAluBEYcH5NrYyc7J68U/wj7LjQqHqkRgPfi3wPGufjJ218W7anu+Pd3k0ScqoC+uVBwNP50XqcmOYO9VhvdF1KAeJB4Z8TbGEraRb/NBafeBaXNxRpmf2YYXMV306rEX3395e+aksOIQmew2+B94nKUCfmFO8YGn9Nu9SgGIf5y5mH10R5og5FklL+4kBcWiKDmYwxafevQQ+JppdLZEWBY9PgJ628ad4qA7GE3LEobc=

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSVER: Visual Studio 14 2015 Win64
      MSBUILD: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSVER: Visual Studio 15 2017 Win64
      MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VSVER: Visual Studio 16 2019
      MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe

configuration: Release

install:
  - ps: nuget install OpenBLAS -o "${env:APPVEYOR_BUILD_FOLDER}"

build_script:
  # First, download and build Armadillo.
  - cd ..
  - appveyor DownloadFile %ARMADILLO_DOWNLOAD% -FileName armadillo.tar.xz
  - 7z x armadillo.tar.xz -so -txz | 7z x -si -ttar > nul
  - cd armadillo-8.400.0 && mkdir build && cd build
  - >
    cmake -G "%VSVER%"
    -DBLAS_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DCMAKE_PREFIX:FILEPATH="%APPVEYOR_BUILD_FOLDER%/armadillo"
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_BUILD_TYPE=Release ..
  - >
    "%MSBUILD%" "armadillo.sln"
    /m /verbosity:quiet /p:Configuration=Release;Platform=x64
  - cd ../..

  # Now build ensmallen.
  - cd ensmallen && mkdir build && cd build
  - >
    cmake -G "%VSVER%"
    -DARMADILLO_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/../armadillo-8.400.0/include/
    -DARMADILLO_LIBRARIES=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY=%BLAS_LIBRARY%
    -DBLAS_LIBRARY=%BLAS_LIBRARY%
    -DCMAKE_BUILD_TYPE=Release ..
  - >
    "%MSBUILD%" "ensmallen.sln"
    /m /verbosity:minimal /nologo /p:BuildInParallel=true

  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  # Run tests after copying libraries.
  - ps: cp C:\projects\ensmallen\OpenBLAS.0.2.14.1\lib\native\bin\x64\*.* C:\projects\ensmallen\build\
  - ctest -C Release -V --output-on-failure .
